steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/kemahasiswaan", "."]
    dir: "backend"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/kemahasiswaan"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - kemahasiswaan
      - --image
      - gcr.io/$PROJECT_ID/kemahasiswaan
      - --timeout
      - 1000s
      - --port
      - "5000"
      - --region
      - us-central1
      - --allow-unauthenticated
      - --set-env-vars
      - MYSQL_DB_HOST=${_MYSQL_DB_HOST},MYSQL_DB_NAME=${_MYSQL_DB_NAME},MYSQL_DB_PASSWORD=${_MYSQL_DB_PASSWORD},MYSQL_DB_USERNAME=${_MYSQL_DB_USERNAME},PG_DB_HOST=${_PG_DB_HOST},PG_DB_NAME=${_PG_DB_NAME},PG_DB_PASSWORD=${_PG_DB_PASSWORD},PG_DB_USERNAME=${_PG_DB_USERNAME},ACCESS_TOKEN_SECRET=${_ACCESS_TOKEN_SECRET},REFRESH_TOKEN_SECRET=${_REFRESH_TOKEN_SECRET}

options:
  logging: CLOUD_LOGGING_ONLY
